#!/usr/bin/env bash
# configure a server to listening on port 80 of all servers active IPV4 IPs

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
