#!/usr/bin/env bash
# Creates an RSA key pair
# Name of the created private key must be school
# Number of bits must be 4096
# The key must be protected by the paraphrase betty

ssh-keygen -b 4096 -f school -t rsa -N betty
